# Generated by Django 3.2.20 on 2023-09-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
