# Generated by Django 3.2.21 on 2023-09-12 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain letters and spaces', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
